### PR TITLE
[AllBundles] Fix Event class and EventDispatcher argument order deprecations

### LINKED ISSUE #2722: EventDispatcher deprecations
User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.

Example: /vendor/kunstmaan/bundles-cms/src/Kunstmaan/NodeBundle/EventListener/SlugListener.php:82

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | fixes #2722

### CODE REVIEW

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Review by dannyvw — APPROVED** [review]

File: src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php [hunk 1]
```diff
@@ -679,7 +680,8 @@ protected function renderDefaultSearchView(
     protected function addCustomData(HasNodeInterface $page, &$doc)
     {
         $event = new IndexNodeEvent($page, $doc);
-        $this->container->get('event_dispatcher')->dispatch(IndexNodeEvent::EVENT_INDEX_NODE, $event);
+        $eventDispatcher = LegacyEventDispatcherProxy::decorate($this->container->get('event_dispatcher'));
```
Comment (Numkil) [inline src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php:683]: Op verschillende andere plaatsen controleren we of deze class eerst bestaat. hoeven we dit hier niet te doen?

Comment (acrobat) [reply src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php]: Good catch! Fixed!
